### PR TITLE
Add exempt codes to validation bubbles

### LINKED ISSUE #2: Add Exemption Codes to Field Annotations
Exemption codes can be found in [Issue 1912](https://github.com/cfpb/hmda-platform/issues/1912) on the hmda-platform repo.

### PR DESCRIPTION
**Pull request by kgudel**
Closes #2

### CODE REVIEW

**Comment by keileyo** [comment]
A few things that need to be updated:

1.  The exemption for ULI is not "Exempt." It is a Non-universal Loan Identifier (NULI) up to 22 characters. 
2. Co-applicant or Co-borrower, Name and Version of Credit Scoring Model is missing 1111. Exempt as an option
3. Interest only payments is missing 1111. Exempt as an option
4. Submission of Application is missing 1111. Exempt as an option

**Comment by kgudel** [comment]
I have corrected points 1, 3, and 4. I rechecked and I do see 1111 in the list for `Co-applicant or Co-borrower, Name and Version of Credit Scoring Model`. Do you mind checking again?

**Comment by chynnakeys** [comment]
@kgudel I'm having an issue expanding the annotations for each cell in the LARFT. I know you haven't merged this PR yet, but is this something you can check out? Here's a screenshot of what I see. 
image

**Comment by keileyo** [comment]
Here is what i see for co-applicant or co-borrower name & version of credit scoring model. I do not see the exempt code. 

image

**Comment by keileyo** [comment]
@kgudel its come to my attention that on the new bureau dell laptops, the macros have been disabled for security reasons & we aren't able to change those settings in the trust center. i opened a ticket w/ the service desk, but wondering if that may be contributing to the issue that @chynnakeys reported or even why i may be seeing something different in the credit scoring comment box (in general, i dont have the same issue as chynna, but other users at the bureau are reporting not being able to view the comment boxes in full). 

image

**Comment by kgudel** [comment]
These changes included in #4

**Pull request closed without merging**
